-- Generated from the EF Core model by SchemaScriptTests. Do not hand-edit.
-- Regenerate by deleting this file and re-running the test.
--
-- This service OWNS the seo schema and nothing else. company_job belongs to the Node
-- application and is reached ONLY through a read-only, keyless projection — there is
-- no write path to it anywhere in this service, guarded and reviewable or otherwise.
--
-- Applied automatically at startup by DatabaseMigrator, serialised across replicas by
-- a Postgres advisory lock. Set Persistence:MigrateOnStartup=false to apply this file
-- as a one-shot job instead, in which case the running service needs no DDL rights.

CREATE SCHEMA IF NOT EXISTS seo;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'seo') THEN
        CREATE SCHEMA seo;
    END IF;
END $EF$;
CREATE TABLE seo."InboxState" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "MessageId" uuid NOT NULL,
    "ConsumerId" uuid NOT NULL,
    "LockId" uuid NOT NULL,
    "RowVersion" bytea,
    "Received" timestamp with time zone NOT NULL,
    "ReceiveCount" integer NOT NULL,
    "ExpirationTime" timestamp with time zone,
    "Consumed" timestamp with time zone,
    "Delivered" timestamp with time zone,
    "LastSequenceNumber" bigint,
    CONSTRAINT "PK_InboxState" PRIMARY KEY ("Id"),
    CONSTRAINT "AK_InboxState_MessageId_ConsumerId" UNIQUE ("MessageId", "ConsumerId")
);
CREATE TABLE seo."OutboxState" (
    "OutboxId" uuid NOT NULL,
    "LockId" uuid NOT NULL,
    "RowVersion" bytea,
    "Created" timestamp with time zone NOT NULL,
    "Delivered" timestamp with time zone,
    "LastSequenceNumber" bigint,
    CONSTRAINT "PK_OutboxState" PRIMARY KEY ("OutboxId")
);
CREATE TABLE seo.seo_facet_state (
    facet_path character varying(512) NOT NULL,
    axes integer NOT NULL,
    job_count integer NOT NULL,
    indexable boolean NOT NULL,
    last_modified timestamp with time zone NOT NULL,
    CONSTRAINT "PK_seo_facet_state" PRIMARY KEY (facet_path)
);
CREATE TABLE seo.seo_rebuild_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    file character varying(128) NOT NULL,
    sitemap_type character varying(32) NOT NULL,
    url_count integer NOT NULL,
    checksum character varying(64) NOT NULL,
    uncompressed_bytes bigint NOT NULL,
    uploaded boolean NOT NULL,
    generated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_seo_rebuild_log" PRIMARY KEY (id)
);
CREATE TABLE seo.seo_url_state (
    job_uid character varying(64) NOT NULL,
    slug character varying(500) NOT NULL,
    status integer NOT NULL,
    last_modified timestamp with time zone,
    dirty boolean NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_seo_url_state" PRIMARY KEY (job_uid)
);
CREATE TABLE seo."OutboxMessage" (
    "SequenceNumber" bigint GENERATED BY DEFAULT AS IDENTITY,
    "EnqueueTime" timestamp with time zone,
    "SentTime" timestamp with time zone NOT NULL,
    "Headers" text,
    "Properties" text,
    "InboxMessageId" uuid,
    "InboxConsumerId" uuid,
    "OutboxId" uuid,
    "MessageId" uuid NOT NULL,
    "ContentType" character varying(256) NOT NULL,
    "MessageType" text NOT NULL,
    "Body" text NOT NULL,
    "ConversationId" uuid,
    "CorrelationId" uuid,
    "InitiatorId" uuid,
    "RequestId" uuid,
    "SourceAddress" character varying(256),
    "DestinationAddress" character varying(256),
    "ResponseAddress" character varying(256),
    "FaultAddress" character varying(256),
    "ExpirationTime" timestamp with time zone,
    CONSTRAINT "PK_OutboxMessage" PRIMARY KEY ("SequenceNumber"),
    CONSTRAINT "FK_OutboxMessage_InboxState_InboxMessageId_InboxConsumerId" FOREIGN KEY ("InboxMessageId", "InboxConsumerId") REFERENCES seo."InboxState" ("MessageId", "ConsumerId"),
    CONSTRAINT "FK_OutboxMessage_OutboxState_OutboxId" FOREIGN KEY ("OutboxId") REFERENCES seo."OutboxState" ("OutboxId")
);
CREATE INDEX "IX_InboxState_Delivered" ON seo."InboxState" ("Delivered");
CREATE INDEX "IX_OutboxMessage_EnqueueTime" ON seo."OutboxMessage" ("EnqueueTime");
CREATE INDEX "IX_OutboxMessage_ExpirationTime" ON seo."OutboxMessage" ("ExpirationTime");
CREATE UNIQUE INDEX "IX_OutboxMessage_InboxMessageId_InboxConsumerId_SequenceNumber" ON seo."OutboxMessage" ("InboxMessageId", "InboxConsumerId", "SequenceNumber");
CREATE UNIQUE INDEX "IX_OutboxMessage_OutboxId_SequenceNumber" ON seo."OutboxMessage" ("OutboxId", "SequenceNumber");
CREATE INDEX "IX_OutboxState_Created" ON seo."OutboxState" ("Created");
CREATE INDEX ix_seo_facet_state_indexable ON seo.seo_facet_state (indexable) WHERE indexable = true;
CREATE INDEX ix_seo_rebuild_log_file_generated_at ON seo.seo_rebuild_log (file, generated_at DESC);
CREATE INDEX ix_seo_url_state_dirty ON seo.seo_url_state (dirty) WHERE dirty = true;
CREATE INDEX ix_seo_url_state_status_job_uid ON seo.seo_url_state (status, job_uid);